//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleManagerLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response
    {
        public int Id { get; set; }
        public string String { get; set; }
        public int Integer { get; set; }
        public double Double { get; set; }
        public byte[] File { get; set; }
        public bool Boolean { get; set; }
        public System.DateTime EndDate { get; set; }
        public int Question_Id { get; set; }
        public int Milestone_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public bool Completed { get; set; }
        public bool Successful { get; set; }
    
        public virtual Milestone Milestone { get; set; }
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
    }
}
